###
GET http://localhost:3000/categories/?take=30&skip=0
###
GET http://localhost:3000/categories/

###
GET http://localhost:3000/categories/1
###
POST http://localhost:3000/categories/ 
Content-Type: application/json

{
  "nom": "philosophie"
}
###
PATCH  http://localhost:3000/categories/
Content-Type: application/json

{

    "id": 3,
    "nom": "philo"
}

###
DELETE http://localhost:3000/categories/3

