###login user
POST http://localhost:3000/login 
Content-Type: application/json

{
     "email": "Myriam_Morar58@gmail.com",
    "Password": "H4lSgRgvZ0MI7Xc"
}

###logout user
POST http://localhost:3000/logout

###get users
GET http://localhost:3000/users/?take=9&skip=0

###get user by id
GET http://localhost:3000/users/4

###create user
POST http://localhost:3000/users/ 
Content-Type: application/json

{
  "nom": "fifi",
  "email": "fifi@gmail.com",
  "Password": "0000",
  "role": "ADMIN"
}

###update user
PATCH  http://localhost:3000/users/ 
Content-Type: application/json


{
  "id":16,
  "nom": "karima",
  "email": "karima@gmail.com",
  "Password": "0000",
  "role": "ADMIN"
}

###delete user
DELETE   http://localhost:3000/users/16

